spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/svj
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    properties:
#      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:9595


  cloud:
    function:
      definition: processOrder
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:29092}
      bindings:
        processOrder-in-0:
          destination: ecommerce-topic3
          group: myGroup
#      kafka:
#        streams:
#          binder:
#            brokers: localhost:29092

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

server:
  port: 9898